### ISSUE TITLE
CS:GO update 2023-02-02 broken gamedata

### ISSUE THREAD

**Issue by Ketz1337** [OkyHp/Default-Balancer#1]
The latest CS:GO update broke the gamedata file.

Error log:
**L 02/04/2023 - 06:14:17: [SM] Exception reported: Failed to setup CCSGameRules::BalanceTeams
L 02/04/2023 - 06:14:17: [SM] Blaming: auto_team_balancer.smx
L 02/04/2023 - 06:14:17: [SM] Call stack trace:
L 02/04/2023 - 06:14:17: [SM]   [0] SetFailState
L 02/04/2023 - 06:14:17: [SM]   [1] Line 47, auto_team_balancer.sp::OnPluginStart
L 02/04/2023 - 06:14:17: [SM] Unable to load plugin "auto_team_balancer.smx": Error detected in plugin startup (see error logs)**

**Comment by OkyHp** [comment]
[Update](https://github.com/OkyHp/Default-Balancer/releases/tag/1.0.2)

**Comment by 1heavy** [comment]
u are a bad boy
